# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddNewPartner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewPartner(object):
    def setupUi(self, AddNewPartner):
        AddNewPartner.setObjectName("AddNewPartner")
        AddNewPartner.resize(370, 344)
        AddNewPartner.setMinimumSize(QtCore.QSize(370, 344))
        AddNewPartner.setMaximumSize(QtCore.QSize(370, 344))
        AddNewPartner.setLayoutDirection(QtCore.Qt.LeftToRight)
        AddNewPartner.setStyleSheet("background-color:#123456;")
        self.centralwidget = QtWidgets.QWidget(AddNewPartner)
        self.centralwidget.setObjectName("centralwidget")
        self.NameCompany = QtWidgets.QLineEdit(self.centralwidget)
        self.NameCompany.setGeometry(QtCore.QRect(10, 50, 341, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.NameCompany.setFont(font)
        self.NameCompany.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;\n"
"")
        self.NameCompany.setInputMask("")
        self.NameCompany.setText("")
        self.NameCompany.setObjectName("NameCompany")
        self.typeCompanyCheckBox = QtWidgets.QComboBox(self.centralwidget)
        self.typeCompanyCheckBox.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.typeCompanyCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.typeCompanyCheckBox.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;\n"
"\n"
"color: black;\n"
"pading: 0px;\n"
"")
        self.typeCompanyCheckBox.setObjectName("typeCompanyCheckBox")
        self.typeCompanyCheckBox.addItem("")
        self.typeCompanyCheckBox.addItem("")
        self.typeCompanyCheckBox.addItem("")
        self.typeCompanyCheckBox.addItem("")
        self.FIODirector = QtWidgets.QLineEdit(self.centralwidget)
        self.FIODirector.setGeometry(QtCore.QRect(10, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.FIODirector.setFont(font)
        self.FIODirector.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;")
        self.FIODirector.setInputMask("")
        self.FIODirector.setText("")
        self.FIODirector.setObjectName("FIODirector")
        self.addNewPartnerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewPartnerButton.setGeometry(QtCore.QRect(10, 250, 171, 51))
        self.addNewPartnerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewPartnerButton.setStyleSheet("QPushButton {\n"
"background-color: 666000;\n"
"\n"
"border: 6px;\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(255, 195, 97);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(255, 195, 97);\n"
"}\n"
"\n"
"")
        self.addNewPartnerButton.setText("Внести")
        self.addNewPartnerButton.setObjectName("addNewPartnerButton")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(190, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.email.setFont(font)
        self.email.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;")
        self.email.setInputMask("")
        self.email.setText("")
        self.email.setObjectName("email")
        self.number = QtWidgets.QLineEdit(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(10, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.number.setFont(font)
        self.number.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;")
        self.number.setInputMask("")
        self.number.setText("")
        self.number.setObjectName("number")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(190, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.address.setFont(font)
        self.address.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;")
        self.address.setInputMask("")
        self.address.setText("")
        self.address.setObjectName("address")
        self.INN = QtWidgets.QLineEdit(self.centralwidget)
        self.INN.setGeometry(QtCore.QRect(10, 170, 341, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.INN.setFont(font)
        self.INN.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;")
        self.INN.setInputMask("")
        self.INN.setText("")
        self.INN.setObjectName("INN")
        self.rating = QtWidgets.QSpinBox(self.centralwidget)
        self.rating.setGeometry(QtCore.QRect(10, 210, 241, 31))
        self.rating.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rating.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;")
        self.rating.setMinimum(1)
        self.rating.setMaximum(10)
        self.rating.setObjectName("rating")
        AddNewPartner.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddNewPartner)
        self.statusbar.setObjectName("statusbar")
        AddNewPartner.setStatusBar(self.statusbar)

        self.retranslateUi(AddNewPartner)
        QtCore.QMetaObject.connectSlotsByName(AddNewPartner)

    def retranslateUi(self, AddNewPartner):
        _translate = QtCore.QCoreApplication.translate
        AddNewPartner.setWindowTitle(_translate("AddNewPartner", "Добавление нового партнёра"))
        self.NameCompany.setPlaceholderText(_translate("AddNewPartner", "Наименование"))
        self.typeCompanyCheckBox.setItemText(0, _translate("AddNewPartner", "ООО"))
        self.typeCompanyCheckBox.setItemText(1, _translate("AddNewPartner", "ОАО"))
        self.typeCompanyCheckBox.setItemText(2, _translate("AddNewPartner", "ПАО"))
        self.typeCompanyCheckBox.setItemText(3, _translate("AddNewPartner", "ЗАО"))
        self.FIODirector.setPlaceholderText(_translate("AddNewPartner", "ФИО Директора"))
        self.email.setPlaceholderText(_translate("AddNewPartner", " Почта"))
        self.number.setPlaceholderText(_translate("AddNewPartner", " Телефон"))
        self.address.setPlaceholderText(_translate("AddNewPartner", "Адрес"))
        self.INN.setPlaceholderText(_translate("AddNewPartner", " ИНН"))
