# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddNewSupplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewSupplier(object):
    def setupUi(self, AddNewSupplier):
        AddNewSupplier.setObjectName("AddNewSupplier")
        AddNewSupplier.resize(399, 171)
        AddNewSupplier.setMinimumSize(QtCore.QSize(399, 171))
        AddNewSupplier.setMaximumSize(QtCore.QSize(399, 171))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images/Мастер пол.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddNewSupplier.setWindowIcon(icon)
        AddNewSupplier.setStyleSheet("background-color: #123456;")
        self.centralwidget = QtWidgets.QWidget(AddNewSupplier)
        self.centralwidget.setObjectName("centralwidget")
        self.FIOSuppliers = QtWidgets.QLineEdit(self.centralwidget)
        self.FIOSuppliers.setGeometry(QtCore.QRect(20, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.FIOSuppliers.setFont(font)
        self.FIOSuppliers.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"\n"
"color:black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n")
        self.FIOSuppliers.setInputMask("")
        self.FIOSuppliers.setText("")
        self.FIOSuppliers.setObjectName("FIOSuppliers")
        self.typeSupplier = QtWidgets.QLineEdit(self.centralwidget)
        self.typeSupplier.setGeometry(QtCore.QRect(20, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.typeSupplier.setFont(font)
        self.typeSupplier.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"\n"
"color: black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n")
        self.typeSupplier.setInputMask("")
        self.typeSupplier.setText("")
        self.typeSupplier.setObjectName("typeSupplier")
        self.INNSuplier = QtWidgets.QLineEdit(self.centralwidget)
        self.INNSuplier.setGeometry(QtCore.QRect(20, 120, 241, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.INNSuplier.setFont(font)
        self.INNSuplier.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"\n"
"color:black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n")
        self.INNSuplier.setInputMask("")
        self.INNSuplier.setText("")
        self.INNSuplier.setObjectName("INNSuplier")
        self.addNewSuppliers = QtWidgets.QPushButton(self.centralwidget)
        self.addNewSuppliers.setGeometry(QtCore.QRect(270, 120, 111, 31))
        self.addNewSuppliers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewSuppliers.setStyleSheet("QPushButton {\n"
"background-color: white;border-radius: 10px;\n"
"\n"
"border: 6px;\n"
"color:black;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.addNewSuppliers.setIconSize(QtCore.QSize(18, 18))
        self.addNewSuppliers.setObjectName("addNewSuppliers")
        AddNewSupplier.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddNewSupplier)
        self.statusbar.setObjectName("statusbar")
        AddNewSupplier.setStatusBar(self.statusbar)

        self.retranslateUi(AddNewSupplier)
        QtCore.QMetaObject.connectSlotsByName(AddNewSupplier)

    def retranslateUi(self, AddNewSupplier):
        _translate = QtCore.QCoreApplication.translate
        AddNewSupplier.setWindowTitle(_translate("AddNewSupplier", "Добавление нового поставщика"))
        self.FIOSuppliers.setPlaceholderText(_translate("AddNewSupplier", " Фамилия Имя Отчество"))
        self.typeSupplier.setPlaceholderText(_translate("AddNewSupplier", " Тип поставок"))
        self.INNSuplier.setPlaceholderText(_translate("AddNewSupplier", " ИНН"))
        self.addNewSuppliers.setText(_translate("AddNewSupplier", "Внести"))
