# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(627, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images/Мастер пол.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Menu.setWindowIcon(icon)
        Menu.setAccessibleName("")
        Menu.setStyleSheet("background-color: #123456;\n"
"padding: 0;\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.suppliersButton = QtWidgets.QPushButton(self.centralwidget)
        self.suppliersButton.setGeometry(QtCore.QRect(330, 320, 261, 41))
        self.suppliersButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suppliersButton.setStyleSheet("QPushButton {\n"
"background-color: #666000;\n"
"border: 9px;\n"
"color:BLACK;\n"
"font: 87 10pt \\\"TimesNewRoman\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.suppliersButton.setObjectName("suppliersButton")
        self.partnerButton = QtWidgets.QPushButton(self.centralwidget)
        self.partnerButton.setGeometry(QtCore.QRect(330, 390, 261, 41))
        self.partnerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.partnerButton.setStyleSheet("QPushButton {\n"
"background-color: #666000;\n"
"border: 9px;\n"
"color:BLACK;\n"
"font: 87 10pt \\\"TimesNewRoman\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.partnerButton.setObjectName("partnerButton")
        self.suppliersButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.suppliersButton_3.setGeometry(QtCore.QRect(330, 460, 261, 41))
        self.suppliersButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suppliersButton_3.setStyleSheet("QPushButton {\n"
"background-color:#666000;\n"
"border: 9px;\n"
"color:BLACK;\n"
"font: 87 10pt \\\"TimesNewRoman\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.suppliersButton_3.setObjectName("suppliersButton_3")
        self.suppliersButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.suppliersButton_4.setGeometry(QtCore.QRect(60, 320, 261, 41))
        self.suppliersButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suppliersButton_4.setStyleSheet("QPushButton {\n"
"background-color: #666000;\n"
"border: 9px;\n"
"color:BLACK;\n"
"font: 87 10pt \\\"TimesNewRoman\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.suppliersButton_4.setObjectName("suppliersButton_4")
        self.suppliersButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.suppliersButton_5.setGeometry(QtCore.QRect(60, 390, 261, 41))
        self.suppliersButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suppliersButton_5.setStyleSheet("QPushButton {\n"
"background-color:#666000;\n"
"border: 9px;\n"
"color:BLACK;\n"
"font: 87 10pt \\\"TimesNewRoman\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.suppliersButton_5.setObjectName("suppliersButton_5")
        self.suppliersButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.suppliersButton_6.setGeometry(QtCore.QRect(60, 460, 261, 41))
        self.suppliersButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suppliersButton_6.setStyleSheet("QPushButton {\n"
"background-color: #666000;\n"
"border: 9px;\n"
"color:BLACK;\n"
"font: 87 10pt \\\"TimesNewRoman\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.suppliersButton_6.setObjectName("suppliersButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 200, 200))
        self.label_2.setMinimumSize(QtCore.QSize(200, 200))
        self.label_2.setStyleSheet("color:rgb(203, 201, 195)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\images/Мастер пол.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.FIOperson = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.FIOperson.setGeometry(QtCore.QRect(200, 220, 221, 61))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.FIOperson.setFont(font)
        self.FIOperson.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.FIOperson.setStyleSheet("background-color:#666000;\n"
"border: 0;\n"
"\n"
"align-items: center;\n"
"font: 87 20pt \\\"Segoe UI Black\\\";\\n\n"
"\n"
"")
        self.FIOperson.setReadOnly(True)
        self.FIOperson.setObjectName("FIOperson")
        Menu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Меню"))
        self.suppliersButton.setText(_translate("Menu", "Поставщики"))
        self.partnerButton.setText(_translate("Menu", "Партнёры"))
        self.suppliersButton_3.setText(_translate("Menu", "История заказов"))
        self.suppliersButton_4.setText(_translate("Menu", "Заявки"))
        self.suppliersButton_5.setText(_translate("Menu", "Сотрудники"))
        self.suppliersButton_6.setText(_translate("Menu", "Продукты"))
        self.FIOperson.setPlainText(_translate("Menu", "MASTER POOL"))
