# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Partner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Partner(object):
    def setupUi(self, Partner):
        Partner.setObjectName("Partner")
        Partner.resize(739, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images/Мастер пол.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Partner.setWindowIcon(icon)
        Partner.setStyleSheet("background-color: #123456;")
        self.centralwidget = QtWidgets.QWidget(Partner)
        self.centralwidget.setObjectName("centralwidget")
        self.tablePartner = QtWidgets.QTableWidget(self.centralwidget)
        self.tablePartner.setGeometry(QtCore.QRect(20, 70, 700, 241))
        self.tablePartner.setAcceptDrops(False)
        self.tablePartner.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color:#666000;\n"
"border-radius: 15px;")
        self.tablePartner.setDragEnabled(False)
        self.tablePartner.setAlternatingRowColors(False)
        self.tablePartner.setObjectName("tablePartner")
        self.tablePartner.setColumnCount(9)
        self.tablePartner.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePartner.setHorizontalHeaderItem(8, item)
        self.tablePartner.horizontalHeader().setCascadingSectionResizes(False)
        self.tablePartner.verticalHeader().setSortIndicatorShown(False)
        self.addNewPartnerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewPartnerButton.setGeometry(QtCore.QRect(20, 20, 261, 41))
        self.addNewPartnerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewPartnerButton.setToolTip("")
        self.addNewPartnerButton.setStyleSheet("QPushButton {\n"
"background-color:#666000;\n"
"\n"
"border: 6px;\n"
"color:black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.addNewPartnerButton.setObjectName("addNewPartnerButton")
        Partner.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Partner)
        self.statusbar.setObjectName("statusbar")
        Partner.setStatusBar(self.statusbar)

        self.retranslateUi(Partner)
        QtCore.QMetaObject.connectSlotsByName(Partner)

    def retranslateUi(self, Partner):
        _translate = QtCore.QCoreApplication.translate
        Partner.setWindowTitle(_translate("Partner", "Партнёры"))
        self.tablePartner.setSortingEnabled(False)
        item = self.tablePartner.horizontalHeaderItem(0)
        item.setText(_translate("Partner", "№"))
        item = self.tablePartner.horizontalHeaderItem(1)
        item.setText(_translate("Partner", "Тип"))
        item = self.tablePartner.horizontalHeaderItem(2)
        item.setText(_translate("Partner", "Название"))
        item = self.tablePartner.horizontalHeaderItem(3)
        item.setText(_translate("Partner", "Директор"))
        item = self.tablePartner.horizontalHeaderItem(4)
        item.setText(_translate("Partner", "Почта"))
        item = self.tablePartner.horizontalHeaderItem(5)
        item.setText(_translate("Partner", "Телефон"))
        item = self.tablePartner.horizontalHeaderItem(6)
        item.setText(_translate("Partner", "Адрес"))
        item = self.tablePartner.horizontalHeaderItem(7)
        item.setText(_translate("Partner", "ИНН"))
        item = self.tablePartner.horizontalHeaderItem(8)
        item.setText(_translate("Partner", "Рейтинг"))
        self.addNewPartnerButton.setText(_translate("Partner", "Добавить нового партнёра"))
