# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Suppliers.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suppliers(object):
    def setupUi(self, Suppliers):
        Suppliers.setObjectName("Suppliers")
        Suppliers.resize(738, 270)
        Suppliers.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Suppliers.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../Downloads/Мастер пол.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Suppliers.setWindowIcon(icon)
        Suppliers.setStyleSheet("background-color:#123456;\n"
"padding: 0;\n"
"")
        self.centralwidget = QtWidgets.QWidget(Suppliers)
        self.centralwidget.setObjectName("centralwidget")
        self.tableSuppliers = QtWidgets.QTableWidget(self.centralwidget)
        self.tableSuppliers.setGeometry(QtCore.QRect(20, 70, 700, 171))
        self.tableSuppliers.setAcceptDrops(False)
        self.tableSuppliers.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color:#666000;")
        self.tableSuppliers.setDragEnabled(False)
        self.tableSuppliers.setAlternatingRowColors(False)
        self.tableSuppliers.setObjectName("tableSuppliers")
        self.tableSuppliers.setColumnCount(5)
        self.tableSuppliers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(4, item)
        self.tableSuppliers.horizontalHeader().setCascadingSectionResizes(False)
        self.tableSuppliers.verticalHeader().setSortIndicatorShown(False)
        self.findSuppliers = QtWidgets.QLineEdit(self.centralwidget)
        self.findSuppliers.setGeometry(QtCore.QRect(290, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("\"Segoe UI Black\"")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.findSuppliers.setFont(font)
        self.findSuppliers.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color:#white;\n"
"\n"
"color: black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n")
        self.findSuppliers.setInputMask("")
        self.findSuppliers.setText("")
        self.findSuppliers.setObjectName("findSuppliers")
        self.addNewSupplierButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewSupplierButton.setGeometry(QtCore.QRect(20, 20, 261, 41))
        self.addNewSupplierButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewSupplierButton.setStyleSheet("background-color:#666000;\n"
"\n"
"border: 6px;\n"
"color: black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n")
        self.addNewSupplierButton.setObjectName("addNewSupplierButton")
        Suppliers.setCentralWidget(self.centralwidget)

        self.retranslateUi(Suppliers)
        QtCore.QMetaObject.connectSlotsByName(Suppliers)

    def retranslateUi(self, Suppliers):
        _translate = QtCore.QCoreApplication.translate
        Suppliers.setWindowTitle(_translate("Suppliers", "Поставщики"))
        self.tableSuppliers.setSortingEnabled(False)
        item = self.tableSuppliers.horizontalHeaderItem(0)
        item.setText(_translate("Suppliers", "№"))
        item = self.tableSuppliers.horizontalHeaderItem(1)
        item.setText(_translate("Suppliers", "ФИО"))
        item = self.tableSuppliers.horizontalHeaderItem(2)
        item.setText(_translate("Suppliers", "История"))
        item = self.tableSuppliers.horizontalHeaderItem(3)
        item.setText(_translate("Suppliers", "Тип"))
        item = self.tableSuppliers.horizontalHeaderItem(4)
        item.setText(_translate("Suppliers", "ИНН"))
        self.findSuppliers.setPlaceholderText(_translate("Suppliers", " Поиск"))
        self.addNewSupplierButton.setText(_translate("Suppliers", "Добавить нового поставщика"))
