# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Orders.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zayavki(object):
    def setupUi(self, Zayavki):
        Zayavki.setObjectName("Zayavki")
        Zayavki.resize(739, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images/Мастер пол.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Zayavki.setWindowIcon(icon)
        Zayavki.setStyleSheet("background-color: #123456;")
        self.centralwidget = QtWidgets.QWidget(Zayavki)
        self.centralwidget.setObjectName("centralwidget")
        self.tableZayavki = QtWidgets.QTableWidget(self.centralwidget)
        self.tableZayavki.setGeometry(QtCore.QRect(20, 70, 700, 241))
        self.tableZayavki.setAcceptDrops(False)
        self.tableZayavki.setStyleSheet("border: 0px;\n"
"max-width: 700px;\n"
"background-color:#666000;\n"
"border-radius: 15px;")
        self.tableZayavki.setDragEnabled(False)
        self.tableZayavki.setAlternatingRowColors(False)
        self.tableZayavki.setObjectName("tableZayavki")
        self.tableZayavki.setColumnCount(9)
        self.tableZayavki.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZayavki.setHorizontalHeaderItem(8, item)
        self.tableZayavki.horizontalHeader().setCascadingSectionResizes(False)
        self.tableZayavki.verticalHeader().setSortIndicatorShown(False)
        self.dobnewzayavka = QtWidgets.QPushButton(self.centralwidget)
        self.dobnewzayavka.setGeometry(QtCore.QRect(20, 20, 261, 41))
        self.dobnewzayavka.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dobnewzayavka.setToolTip("")
        self.dobnewzayavka.setStyleSheet("QPushButton {\n"
"background-color:#666000;\n"
"\n"
"border: 6px;\n"
"color:black;\n"
"font: 87 10pt \\\"Segoe UI Black\\\";\\n\\;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"")
        self.dobnewzayavka.setObjectName("dobnewzayavka")
        Zayavki.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Zayavki)
        self.statusbar.setObjectName("statusbar")
        Zayavki.setStatusBar(self.statusbar)

        self.retranslateUi(Zayavki)
        QtCore.QMetaObject.connectSlotsByName(Zayavki)

    def retranslateUi(self, Zayavki):
        _translate = QtCore.QCoreApplication.translate
        Zayavki.setWindowTitle(_translate("Zayavki", "Заявки"))
        self.tableZayavki.setSortingEnabled(False)
        item = self.tableZayavki.horizontalHeaderItem(0)
        item.setText(_translate("Zayavki", "№"))
        item = self.tableZayavki.horizontalHeaderItem(1)
        item.setText(_translate("Zayavki", "Тип"))
        item = self.tableZayavki.horizontalHeaderItem(2)
        item.setText(_translate("Zayavki", "Название"))
        item = self.tableZayavki.horizontalHeaderItem(3)
        item.setText(_translate("Zayavki", "Директор"))
        item = self.tableZayavki.horizontalHeaderItem(4)
        item.setText(_translate("Zayavki", "Почта"))
        item = self.tableZayavki.horizontalHeaderItem(5)
        item.setText(_translate("Zayavki", "Телефон"))
        item = self.tableZayavki.horizontalHeaderItem(6)
        item.setText(_translate("Zayavki", "Адрес"))
        item = self.tableZayavki.horizontalHeaderItem(7)
        item.setText(_translate("Zayavki", "ИНН"))
        item = self.tableZayavki.horizontalHeaderItem(8)
        item.setText(_translate("Zayavki", "Рейтинг"))
        self.dobnewzayavka.setText(_translate("Zayavki", "Добавить новую заявку"))
